### local.inc --- Lisp local include  makefile for Emacs Lisp libraries

## Copyright (C) 2012 Didier Verna

## Author:     Didier Verna <didier@didierverna.net>
## Maintainer: Didier Verna <didier@didierverna.net>

# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.


### Commentary:


### Code:


## Local Variables:
## mode: makefile
## End:

### local.inc ends here
